# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2892a5def2c7ad629f29cb76a52c9c3c0e8aeb74e9a83fdbfd5b7c6d44e1636c21fe116f1b10861db1f5fb1f17ca864f224ffb9f467e4c699d9e2af71ec7fe69

test:
  secret_key_base: b511ce749feb353eece876ad437f2e98b48e02f9c995d78ba8d8a3e0f3b59961deac9dce9fcbefb9c3d979c97f8ea874e57efa37b9cf0e9b81e76ab89d44a0c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
